In [2]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


In [3]:
# Carregar o Iris Dataset
iris = load_iris()
X = iris.data
y = iris.target


In [4]:
# Dividir os dados em conjuntos de treino e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)


In [5]:
# Treinar o modelo KNN
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)
y_pred_knn = knn.predict(X_test)


In [6]:
# Treinar o modelo SVM
svm = SVC(kernel='linear')
svm.fit(X_train, y_train)
y_pred_svm = svm.predict(X_test)



In [7]:
# Avaliar o desempenho KNN
accuracy_knn = accuracy_score(y_test, y_pred_knn)
report_knn = classification_report(y_test, y_pred_knn)
conf_matrix_knn = confusion_matrix(y_test, y_pred_knn)

print("Desempenho KNN:")
print(f"Acurácia: {accuracy_knn}")
print("Relatório de Classificação:")
print(report_knn)
print("Matriz de Confusão:")
print(conf_matrix_knn)

Desempenho KNN:
Acurácia: 1.0
Relatório de Classificação:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

Matriz de Confusão:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]


In [8]:
# Avaliar o desempenho SVM
accuracy_svm = accuracy_score(y_test, y_pred_svm)
report_svm = classification_report(y_test, y_pred_svm)
conf_matrix_svm = confusion_matrix(y_test, y_pred_svm)

print("\nDesempenho SVM:")
print(f"Acurácia: {accuracy_svm}")
print("Relatório de Classificação:")
print(report_svm)
print("Matriz de Confusão:")
print(conf_matrix_svm)



Desempenho SVM:
Acurácia: 1.0
Relatório de Classificação:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

Matriz de Confusão:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]


In [9]:
# Comparação dos desempenhos
print("\nComparação de Desempenho:")
print(f"Acurácia KNN: {accuracy_knn}")
print(f"Acurácia SVM: {accuracy_svm}")


Comparação de Desempenho:
Acurácia KNN: 1.0
Acurácia SVM: 1.0
